### PR TITLE
Fix exception about "yearDropdownPlugin" when "noCalendar:true".

### PR DESCRIPTION
**Pull request by frck006**
Hi,

I just add a test to add "yearDropdownPlugin"'s plugin only if "noCalendar" is false.

Regard.

### CODE REVIEW

**Comment by kodaicoder** [comment]
did you have try with "time_24hr" options ?
is it work as 24 hours time ?

**Comment by frck006** [comment]
I've just try, but if I set "time_24hr:true", I've the same problem.
I think it's logic, because the problem comes from: 
`function attachFlatpickr(node, opts, plugins = [new yearDropdownPlugin()]) {`
If "datePicker" display calendar with drop dow "year", it'll throw exception. :(
It's for this I've add this condtion:
function attachFlatpickr(node, opts, plugins = opts.noCalendar ? [] : [new yearDropdownPlugin()]) {
If you have another idea, I can test.
Regard.

**Comment by kodaicoder** [comment]
Sorry for late response and review
I just try checking your code again and it all working perfectly find with time picker
but in latest of your pull request commit please remove `dist` and `package.json` file from commit
I will merge your pull request and published it on npm ASAP

Thank you for your hard work 🙏

**Comment by frck006** [comment]
Normaly, I delete "`/dist`" and "`package.json`".
Thanks.

**Pull request merged**
